# Generated by Django 3.2.5 on 2021-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteo_24h',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=20, null=True)),
                ('temp_avg', models.FloatField(null=True)),
                ('temp_max', models.FloatField(null=True)),
                ('temp_min', models.FloatField(null=True)),
                ('hrel_avg', models.FloatField(null=True)),
                ('pressao_avg', models.FloatField(null=True)),
                ('pnmm_avg', models.FloatField(null=True)),
                ('precip_tot', models.FloatField(null=True)),
            ],
        ),
    ]
