# Generated by Django 3.2.5 on 2021-09-15 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Solar_images',
            new_name='Solar_image',
        ),
    ]
