# Generated by Django 3.2.5 on 2021-09-15 22:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_data', '0007_auto_20210915_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar_image',
            name='CN_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='CNspots_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='DOP_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='HAZ_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='HA_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='K1_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='K3_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='K3fac_image',
            field=models.ImageField(null=True, upload_to=datetime.datetime(2021, 9, 15, 23, 21, 11, 983814)),
        ),
    ]
