# Generated by Django 3.2.5 on 2021-09-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_data', '0011_auto_20210916_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solar_image',
            name='CN_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='CNspots_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='DOP_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='HAZ_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='HA_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='K1_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='K3_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='K3fac_image',
            field=models.ImageField(null=True, upload_to='solarData/2021_09_20_20_52'),
        ),
        migrations.AlterField(
            model_name='solar_image',
            name='date',
            field=models.CharField(default='2021_09_20_20_52', max_length=20, null=True),
        ),
    ]
